#!/usr/bin/env python
# coding=utf-8
import os
import subprocess
import pwd
import logging

BITBLOQS_HANDLER1 = """

#custom handler for bitbloqs web2board:
x-scheme-handler/web2board=web2board-handler.desktop
"""
BITBLOQS_HANDLER2 = """

#custom handler for bitbloqs web2board:
x-scheme-handler/web2board=web2board-handler.desktop
#END_WEB2BOARD_HANDLER
"""

DESKTOP_TEXT = """[Desktop Entry]
Version=2.0.0
Type=Application
Icon=/opt/web2board/web2board/res/Web2board.ico
Exec=/opt/web2board/web2boardLink
StartupNotify=true
Terminal=false
Categories=Utility;X-XFCE;X-Xfce-Toplevel
MineType=x-scheme-handler/vnc
Comment=Launch web2board
Name=Web2board Launcher
Name[en_US]=Erb2board
"""

applicationsPath = os.path.join("/usr/share/applications")
mineAppsFilePath = os.path.join(applicationsPath, "defaults.list")
web2boardDesktop = os.path.join(applicationsPath, "web2board-handler.desktop")

def startLogger():
        if os.geteuid() != 0:
            fileHandler = logging.FileHandler("installer.log", 'a')
        else:
            fileHandler = logging.FileHandler("/opt/web2board/installer.log", 'a')
        fileHandler.setLevel(logging.DEBUG)
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        fileHandler.setFormatter(formatter)
        log = logging.getLogger()
        log.addHandler(fileHandler)
        log.setLevel(logging.DEBUG)
        return logging.getLogger(__name__)

def addAllUsersToDialOut():
    allUsers = [p[0] for p in pwd.getpwall()]
    for user in allUsers:
        subprocess.call(["sudo", "adduser", user, "dialout"])

def addHandlerInMimeapps():
    if not os.path.exists(applicationsPath):
        os.makedirs(applicationsPath)

    if os.path.isfile(mineAppsFilePath):
        with open(mineAppsFilePath) as f:
            fContent = f.read()
        fContent = fContent.replace(BITBLOQS_HANDLER2, "")
        fContent = fContent.replace(BITBLOQS_HANDLER1, "")
        if "[Default Applications]" not in fContent:
            fContent = "[Default Applications]\n" + fContent
        with open(mineAppsFilePath, "w") as f:
            f.write(fContent)

    with open(mineAppsFilePath, 'a') as f:
        f.write(BITBLOQS_HANDLER2)

    with open(web2boardDesktop, "w") as f:
        f.write(DESKTOP_TEXT)

if __name__ == '__main__':
    try:
        log = startLogger()
        log.info("Script started")
        log.info("Adding users to dialout")
        addAllUsersToDialOut()
        log.info("Adding handler in Mineapps file: {}".format(mineAppsFilePath))
        addHandlerInMimeapps()
        log.info("Successfully installed web2board")
    except:
        log.exception("Failed performing postinst")
        raise

