#!/bin/bash
 
set -e

BITBLOQLIBS_VERSION=0.0.1

################# REGISTER #################
# echo $USERNAME
# sudo adduser $USERNAME dialout

#Create route if it does not exist previously 
mkdir -p ~/.local/share/applications/


echo "[Desktop Entry]
Version=0.0.1
Type=Application
Exec= xterm -iconic -e web2board
Icon=vncviewer
StartupNotify=true
Terminal=false
Categories=Utility;X-XFCE;X-Xfce-Toplevel;
MimeType=x-scheme-handler/vnc
Name=web2board Launcher
Comment=Launch web2board
Name[en_US]=web2board-handler" > ~/.local/share/applications/web2board-handler.desktop


echo "


#custom handler for bitbloqs web2board:
x-scheme-handler/web2board=web2board-handler.desktop
" >> ~/.local/share/applications/mimeapps.list


################# LIBRARIES #################

#OLDER VERSIONS  --> if home/sketchbook exists, we copy the libraries so they can be used in the old sketchbook directory
if [ -d "$HOME/sketchbook" ]; then
  #Create route if it does not exist previously
  mkdir -p $HOME/sketchbook/libraries/

  #Remove previous bitbloqLibs library if it exists:
  rm -rf $HOME/sketchbook/libraries/bitbloqLibs

  cd $HOME/sketchbook/libraries/

  #Download the new version:
  wget https://github.com/bq/bitbloqLibs/archive/v${BITBLOQLIBS_VERSION}.zip
  unzip v${BITBLOQLIBS_VERSION}.zip -d .
  rm -rf v${BITBLOQLIBS_VERSION}.zip*
  mv bitbloqLibs-${BITBLOQLIBS_VERSION}/* .
  rm -rf bitbloqLibs-${BITBLOQLIBS_VERSION}
fi

#NEWER VERSIONS
#Create route if it does not exist previously
mkdir -p $HOME/Arduino/libraries/

#Remove previous bitbloqLibs library if it exists:
rm -rf $HOME/Arduino/libraries/bitbloqLibs

cd $HOME/Arduino/libraries/

#Download the new version:
wget https://github.com/bq/bitbloqLibs/archive/v${BITBLOQLIBS_VERSION}.zip
unzip v${BITBLOQLIBS_VERSION}.zip -d .
rm -rf v${BITBLOQLIBS_VERSION}.zip*
mv bitbloqLibs-${BITBLOQLIBS_VERSION}/* .
rm -rf bitbloqLibs-${BITBLOQLIBS_VERSION}

exit 0
